### ISSUE TITLE
Greedy has a check using input outside input spec

### ISSUE THREAD

**Issue by mjdv** [minprog/cs50x#21]
(This issue originally talked about an additional problem. I made a mistake there, that was not actually an issue.)

The check for greedy does a check on the code with input `4.209` and expected output `19`. The assignment never makes a reference to fractional cents, and strongly suggests that all output will have at most two digits after the decimal separator (if there is one).

**Comment by WouterVrielink** [comment]
Just some insight; the check with input `4.209` is to prevent students from not properly checking the remainder, ie. `while(remainder != 0.0)` when using floating point arithmetic instead of the intended integer arithmetic.

**Comment by mjdv** [comment]
But ultimately the students are not wrong to do so: a C (32 bit) float can represent integers exactly up to high enough values that it always works for making change. (Specifically, the least integer that is not exactly represented by a 32 bit float is `16,777,217`.) Correction (edit): they are not wrong to do so as long as they round it. The conversion to an `int` however is not necessary for correct functioning of the program.

And, at the point where the input gets that large, the indended solution starts failing anyway: using the line `int cents = round(change * 100);` or something similar, with input `167772.17` gives the value `16777218` in the variable `cents`.

**Comment by stgm** [comment]
Round is niet overbodig. Print maar het float-resultaat van 100 * 4.20 versus de round() van die berekening.

Wordt niet goed uitgelegd waarom dit werkt overigens.

**Comment by mjdv** [comment]
```
#include <stdio.h>
#include <math.h>

int main() {
    float x = 100 * 4.20;
    float y = round(x);
    printf("%f\n", x);
    printf("%f\n", y);
    printf("%d\n", x == y);
}
```
Output:
```
420.000000
420.000000
1
```

**Comment by stgm** [comment]
Oh dat was een beetje dom. Er kán bij de eerste ook 4.19999 uitkomen (maar in jouw geval niet :-)). Bij de tweede niet.

**Comment by mjdv** [comment]
Right, ik snap hem weer. Excuses over de verwarring over `round`. Maar even goed vind ik het problematisch dat er getest wordt met ongeldige input.

**Comment by stgm** [comment]
No worries. Ik vind dat op zich ook onhandig. Laten we even kijken of de test beter geformuleerd kan worden.

**Comment by mjdv** [comment]
Het onderliggende probleem van deze tests is dat de opdracht zelf iets fout doet: geld, zeker als je het gaat hebben over munten, is geen floating-point getal maar een *fixed*-point getal, of in andere woorden een integer aantal centen. De correcte(-re) manier om deze input te lezen zou `scanf("%d.%d", &dollars, &cents); money = 100*dollars + cents;` zijn.

Om deze "fout" te corrigeren, doet de intended solution in plaats daarvan (met `float input`):
```
int cents = round(input * 100);
```

Om deze correctie af te dwingen worden dan een aantal rare tests gebruikt:

* Input `4.209` dwingt je om af te ronden, maar deze past helemaal niet in de inputspecificatie; een correct programma zou hier dan ook mee kunnen doen wat het wil.
* Input `262144.18` dwingt je om een `int cents` te gebruiken in plaats van `float cents`, maar de test is eigenlijk slecht. Aangezien er geen bovengrens gegeven wordt in de input-specificatie weet je helemaal niet wat voor groottes getallen je kunt verwachten. Elk standaard data-type in C gaat fout bij groot genoege getallen, dus in zekere zin is het feit dat een `int` hier wel werkt "toeval". Voor kleine getallen kun je ook prima `float cents` gebruiken, omdat kleine gehele getallen allemaal exact weergegeven kunnen worden in een C `float` (laat staan een C `double`). Maar zelfs als we de inputgrens zo kiezen dat dit getal er net binnen valt is het een oneerlijke test: het feit dat het juiste antwoord eruit komt bij de intended solution is toeval. Als de munt met de grootste waarde 25 zou zijn zou het antwoord fout zijn, en ook op input `262144.19` komt er bij de intended solution het foute antwoord uit.

Ik zie een paar mogelijke oplossingen:

1. De opdracht grondig veranderen: of een probleem kiezen waarbij een float inlezen *wel* relevant is (waardoor de rest van het programma/de tests natuurlijk volgen), ofwel de student aanleren om structured input te lezen. (Dit is waarschijnlijk niet feasible.)
2. De student de "hack" `int cents = round(input * 100);` geven in de opdracht, en erbij zeggen dat dit een trucje is (of in ieder geval niet suggereren dat dit een goede oplossing is).
3. De foute tests verwijderen en de studenten met `float`s laten werken als ze dat willen.

**Comment by stgm** [comment]
In principe zie ik de opdracht juist als een confrontatie met het fundamentele gebrek aan een native fixed-point datatype. Het is wat onhandig allemaal, maar wel een leuke kennismaking.

Nu zie ik in de [opdracht](https://prog120.mprog.nl/problems/greedy) dat we het idee van de hack niet zo héél goed aanreiken. We geven wel `round()` maar niks anders. Het idee is dan dat ze daarmee gaan puzzelen, maar dat zeggen we dan ook weer niet expliciet.

Misschien is het handig eerst nog even een walkthrough-filmpje op te snorren voor de opdracht (greedy of nieuwe naam cash) en te kijken hoe het daar aangereikt wordt. De walkthrough in de gelinkte opdracht is namelijk ingekort tot alleen het concept van het wisselgeld-algoritme.

**Comment by stgm** [comment]
https://www.youtube.com/watch?v=9dZzyl7dCuw

**Comment by stgm** [comment]
@mjdv Kijk maar eens naar bovenstaande walkthrough-filmpje. Ik vind het al veel beter. Het is veel informatie in één keer (de reden dat CS50 te filmpjes steeds korter maakt) maar wel degelijker, iets meer de diepte in.

**Comment by stgm** [comment]
De formule werd sinds afgelopen semester al gegeven in de opdracht. Nu ook een uitleg toegevoegd dat het echt een "hack" is. c2c7cc9
