### ISSUE TITLE
hangman slug

### ISSUE THREAD

**Issue by bjorn-out** [minprog/cs50x#24]
The current structure of the hangman checks will cause an issue when students first run evil and then want to run lovely or vice-versa due to [this issue](https://github.com/cs50/lib50/issues/89).

There are two options: `minprog/cs50x/2019/hangman/evil` and `minprog/cs50x/2019/hangman/lovely` or `minprog/cs50x/2019/evilhangman` and `minprog/cs50x/2019/lovelyhangman`. Which is preferable?

**Comment by stgm** [comment]
We in de komende tijd nog even face-to-face overleggen hierover, maar ook over het ontwerp van deze specifieke checks!

**Comment by stgm** [comment]
Slugs (en naam opdracht) zijn aangepast.
