### ISSUE TITLE
recover doesn't check trying to write to a file that's not open

### ISSUE THREAD

**Issue by stgm** [minprog/cs50x#25]
This happens because the first image in card.raw is not in the first data block of that file. Many people write code that opens a file as soon as a JPEG signature is recognized. But in some code it is assumed to be open and fwrite is called on an null pointer.

This can be prevented by checking the file pointer, or by checking whether we "are at" the first image before writing.

This one is pretty hard to debug so a check might be nice.

**Comment by stgm** [comment]
@bjorn-out Is dit wat voor jou? Ik zou dit wel willen hebben, is een veelvoorkomend probleem bij studenten.

**Comment by bjorn-out** [comment]
Ja, is goed. Ik zal kijken hoe we dit goed kunnen checken.

**Comment by stgm** [comment]
Ik denk dat ik hier bedoelde om een check50-check te schrijven maar ik denk dat dit onmogelijk is.
