### ISSUE TITLE
survey kan niet altijd tekstvelden vinden

### ISSUE THREAD

**Issue by stgm** [minprog/cs50x#27]
https://secure.helpscout.net/conversation/990143676/22236?folderId=194820

**Comment by stgm** [comment]
Volgens Wouter en Quinten komt dit omdat BeautifulSoup misloopt op invalid HTML. Kan BS misschien wat meer losjes ingesteld worden? Of moeten we een validator toevoegen als eerste stap?

**Comment by stgm** [comment]
Ook was er iemand die een syntaxfout had in een application.py, waarmee check50 geen duidelijke feedback gaf.

**Comment by bjorn-out** [comment]
@stgm @Jelleas 
Ik zal morgenavond even kijken naar de mogelijke instellingen voor BeautifulSoup, maar er is ook wat voor te zeggen om een validator toe te voegen. We zouden bijvoorbeeld [deze API](https://validator.w3.org/docs/api.html) kunnen aanroepen. Hiermee zouden we ook behoorlijk specifieke feedback kunnen geven. Mochten we hiervoor geen API willen gebruiken, zijn er ook best libraries verkrijgbaar. Deze geven over het algemeen echter wat minder duidelijke feedback. Mochten we voor de homepage opdracht een check willen toevoegen (mede gelet op WebProg IK waar die opdracht volgens mij ook gebruikt wordt), kunnen we deze hieraan ook toevoegen.

Morgenavond kijk ik even naar beide mogelijkheden en hoe deze werken met check50. Wat vinden jullie ervan om aan deze opdracht een validator toe te voegen?

**Comment by stgm** [comment]
Ik ben zeker voor een validator. Online kan denk ik prima, met een mooie korte timeout. Als het een standaard-validator is dan hoeft de check wat mij betreft alleen maar aan te geven of het "lukt" of "niet lukt", zodat studenten zélf de validator op het web moeten opzoeken voor meer feedback.

**Comment by bjorn-out** [comment]
In beide voorbeelden die ik heb ontvangen kon BeautifulSoup inderdaad bepaalde elementen niet vinden omdat er sprake was van stray start- danwel end-tags. BeautifulSoup raakt daardoor behoorlijk in de war. Anders instellen van BeautifulSoup had waarschijnlijk niet geholpen.

Een validator zou dit probleem inderdaad moeten oplossen. Vandaar dat ik #35 als 'resolves #27' heb gemarkeerd.
