### ISSUE TITLE
Hangman faulty check for length 27 word

### ISSUE THREAD

**Issue by mjdv** [minprog/cs50x#33]
Right now, in the Hangman check, we check that no game can be created for a word of length 27.

However, with the dictionary file currently supplied with the problem, such a word *does* exist: `microspectrophotometrically`.

**Comment by bjorn-out** [comment]
Op zich zou dit geen probleem moeten zijn. De dictionary die wordt gebruikt door de checks heeft het woord 'microspectrophotometrically' namelijk niet. De dictionary in de dist is blijkbaar een andere dictionary.
![Screenshot 2019-11-27 at 14 19 49](https://user-images.githubusercontent.com/38955258/69726734-6a1b7a00-1121-11ea-941a-e3b2bd6ed987.png)

De volgende keer als deze opdracht wordt gebruikt moeten we één van de twee even bijwerken. Voor nu helpt het wellicht om 29 te gebruiken in plaats van 27, die bestaat in beide lijsten niet.
