### ISSUE TITLE
Hangman classic wisselend check resultaat 

### ISSUE THREAD

**Issue by Jelleas** [minprog/cs50x#36]
De check `lose_games`: geeft je 5 guesses voor een 12 letter woord, maar het zou in een niet-evil versie zomaar kunnen dat dat voldoende is. Misschien die woorden uit de dictionary filteren?

**Comment by bjorn-out** [comment]
Dat kan inderdaad, met de woorden 'kinnickinnic' en 'sleeplessess'.

![Screenshot 2019-12-03 at 15 41 03](https://user-images.githubusercontent.com/38955258/70061087-f4f9ea00-15e3-11ea-8c0b-f625466aa1f7.png)

Ik zal ze eruit filteren. Overigens betwijfel ik sowieso of 'sleeplessess' een bestaand woord is.
