### ISSUE TITLE
forced movement check icm description

### ISSUE THREAD

**Issue by stgm** [minprog/cs50x#38]
> In de opdracht staat dat je get_long_description() moet gebruiken voor een forced movement. Maar check50 zoekt op de output die get_description() geeft als de room al gevisit is....

![image](https://user-images.githubusercontent.com/1301531/70123117-45b82400-1672-11ea-859c-97a62071a9d0.png)
![image](https://user-images.githubusercontent.com/1301531/70123120-48b31480-1672-11ea-9a9f-b85db870ca1a.png)

**Comment by bjorn-out** [comment]
Oh, ik zie al wat hier gebeurd is. De manier waarop ik de omschrijving interpreteer is als volgt:
- In de kamer met `FORCED` movement moet `get_long_description` gebruikt worden;
- In de kamer waar je naar terug gaat gebruik je de reguliere `get_description`.

Ik zal dit iets duidelijker maken in de opdrachtomschrijvingen zelf.
