### ISSUE TITLE
Greedy doesn't check for correct input after incorrect input

### ISSUE THREAD

**Issue by WouterVrielink** [minprog/cs50x#56]
Issue as title.

![afbeelding](https://user-images.githubusercontent.com/4168678/74532093-98457480-4f2e-11ea-96f2-0605416bc824.png)

This works, while it clearly shouldn't. Can be fixed by adding a test that enters "foo"  and then "5" or by adding to `test_reject_repeated()`.

**Comment by stgm** [comment]
Fixed in f12084a.
