### ISSUE TITLE
The problem page for problem fifteen-more contains errors.

### ISSUE THREAD

**Issue by mjdv** [minprog/cs50x#59]
The problem page for `fifteen-more` contains some errors.

* The specification for `init()` states: "Implement `init` in such a way that the board is initialized to a pseudorandom but solvable configuration." However, this contracts the Hints section, and also apparently contradicts the check for a 3 x 3 board of fifteen-more, which start with "some random valid moves" -- something you could never know if the board was initialized randomly.
* The page hints at using A*; that seems both unnecessarily complicated and maybe not even sufficient, because it would be too slow and/or use too much memory. (These complaints are related: in a reasonable amount of time, in an efficient implementation, a lack of memory almost always also means a lack of time: modern computers have so much memory that just iterating over all of it takes a long time. And to implement A* with a time complexity approaching linear you need something like a priority queue, something that is quite difficult to implement in C from scratch.) In fact, the next hint agrees with this: it predicts that A* might take too much memory on a 4 x 4 board.  Instead, it suggests "Iterative Deepening A*", and then links to a paper on this -- I didn't read it in full, but I actually think IDA* is even slower than A*? But it does use less space. It also suggests another paper, presumably one that is actually on the N-puzzle, but that link is dead. In general, it seems like the hints here mostly just send students in the wrong and/or confusing directions.

**Comment by stgm** [comment]
Deze more comfy versie is nu vervangen door een versie waarin een random (solvable) configuratie moet worden gegenereerd. Het hele algoritmisch oplossen is daarmee even terzijde geschoven.
