### ISSUE TITLE
Resize, filmpje van less laten zien ik more

### ISSUE THREAD

**Issue by MarijnDoeve** [minprog/cs50x#60]
Er staat best wat uitleg in less die niet in de more walkthrough zit

**Comment by MarijnDoeve** [comment]
Oei, nee dat is al weer een tijdje geleden.

**Comment by mjdv** [comment]
Het is me niet duidelijk over welk probleem dit gaat (welke Less en More?).

Dus allemaal maar:

* Mario: Hier ontbreekt juist een filmpje bij *less*: het is een soort introductie van een filmpje, maar de daadwerkelijke uitleg mist. Bij *more* is de uitleg best uitgebreid.

* Initials: volgens mij zit alle informatie van less ook in more, maar alleen met wat minder nadruk (maar dat moet ook wel in een even lang filmpje). De functie `get_string` wordt genoemd, het feit dat de eerste character een spatie kan zijn, en het feit dat de strings lowercase letters kunnen hebben.

* Find: het more-filmpje is summier, maar ik weet niet of het less-filmpje hier iets toevoegt, omdat die toch vooral gaat over het uitleggen van de less-sorteermethode.

Ik denk niet dat dit aangepast hoeft te worden.

**Comment by stgm** [comment]
Het ging om resize :-) Hebben we die wel in de repo staan?

**Comment by mjdv** [comment]
Oh, ha. Die ken ik niet. Bij welk vak wordt die gebruikt?

**Comment by stgm** [comment]
Programmeren 1:

https://prog120.mprog.nl/problems/resize/less
https://prog120.mprog.nl/problems/resize/more

No worries als je 'm niet kent, dan kijk ik er naar, of iemand anders.

**Comment by stgm** [comment]
Voor zover ik kan zien gaat het vooral om uitgebreidere uitleg over bv. `fseek`. Ik voeg een verwijzing naar de man-pages toe hiervoor.
