### ISSUE TITLE
Fifteen submit

### ISSUE THREAD

**Issue by stgm** [minprog/cs50x#61]
Moet de makefile echt nog ingeleverd worden? Dan misschien instructies opnemen?

**Comment by Jelleas** [comment]
Makefile van welke opdracht?

**Comment by mjdv** [comment]
@Jelleas De `submit.yml` van `fifteen_less` `require`t een Makefile. Overigens wordt die bij het testen geloof ik niet gebruikt.

**Comment by stgm** [comment]
Pas op, de .cs50.yaml van check50 wil 'm ook hebben. (Wat niet wil zeggen dat de check deze gebruikt, maar dat heb ik niet bekeken.)

**Comment by mjdv** [comment]
De check `compiles` in `__init__.py` gebruikt gewoon `check50.c.compile`, en daar komt voor zover ik weet geen Makefile aan te pas.

**Comment by stgm** [comment]
Prima. Kun je dan een PR maken voor het verwijderen van de Makefile uit alle onderdelen? Dan kunnen we het testen met check50 en daarna met de website en een paar studenteninzendingen.
