### ISSUE TITLE
Similarities-more

### ISSUE THREAD

**Issue by WouterVrielink** [minprog/cs50x#62]
In `helpers.py` staat een `Enum` met een `__str__` methode die errors geeft in de IDE (maar wel gewoon werkt). Deze methode is niet nodig, en bemoedigt eigenlijk alleen maar verkeerd gebruik van de class.

**Comment by stgm** [comment]
In de distro: http://cdn.cs50.net/2017/fall/psets/6/similarities/more/similarities.zip

Nu gebruiken we deze opdracht momenteel niet, dus deze gaat naar low priority, en mogelijk verwijderen we deze zomer de opdracht uit de repo.
